export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const REMOVE_BUN: 'REMOVE_BUN' = 'REMOVE_BUN';
export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT: 'REMOVE_INGREDIENT' = 'REMOVE_INGREDIENT';
export const UPDATE_INDREDIENT_LIST: 'UPDATE_INDREDIENT_LIST' = 'UPDATE_INDREDIENT_LIST';
export const CLEAR_INGREDIENTS: 'CLEAR_INGREDIENTS' = 'CLEAR_INGREDIENTS';